apiVersion: apps/v1
kind: Deployment
metadata:
  name: campustrade-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: campustrade
  template:
    metadata:
      labels:
        app: campustrade
    spec:
      containers:
        - name: campustrade
          image: s223399201/campustrade:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: campustrade-service
spec:
  type: LoadBalancer
  selector:
    app: campustrade
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
